// old-react-version/components/Cards/CardGrid.tsx
import React from 'react';
import { CardItem } from './CardItem';
import type { Card } from '../../types';

export interface CardGridProps {
    title: string;
    cards: Card[];
    linkPrefix?: string;
    showDate?: boolean;
    showDescription?: boolean;
}

export const CardGrid: React.FC<CardGridProps> = ({
    title,
    cards,
    linkPrefix,
    showDate = false,
    showDescription = false,
}) => {
    const gridStyle: React.CSSProperties = {
        display: 'flex',
        flexWrap: 'wrap',
        gap: 16,
    };
    const itemStyle: React.CSSProperties = {
        flex: '0 0 calc(33.333% - 16px)',
        boxSizing: 'border-box',
    };

    return (
        <section style={{ maxWidth: 1000, margin: '0 auto', padding: '20px' }}>
            <h2 style={{ fontSize: 24, marginBottom: 16 }}>{title}</h2>
            <div style={gridStyle}>
                {cards.map(card => (
                    <CardItem
                        key={card.id}
                        card={card}
                        showDate={showDate}
                        showDescription={showDescription}
                        linkPrefix={linkPrefix}
                        style={itemStyle}
                    />
                ))}
            </div>
        </section>
    );
};

// src/components/Cards/CardGrid.vue
<template>
  <section :style="sectionStyle">
    <h2 :style="titleStyle">{{ title }}</h2>
    <div :style="gridStyle">
      <CardItem
        v-for="card in cards"
        :key="card.id"
        :card="card"
        :show-date="showDate"
        :show-description="showDescription"
        :link-prefix="linkPrefix"
        :style="itemStyle"
      />
    </div>
  </section>
</template>

<script setup>
import { defineProps } from 'vue'
import CardItem from './CardItem.vue'

const props = defineProps({
  title: {
    type: String,
    required: true
  },
  cards: {
    type: Array,
    required: true
  },
  linkPrefix: {
    type: String,
    default: undefined
  },
  showDate: {
    type: Boolean,
    default: false
  },
  showDescription: {
    type: Boolean,
    default: false
  }
})

// Define styles as reactive objects
const sectionStyle = {
  maxWidth: '1000px',
  margin: '0 auto',
  padding: '20px'
}

const titleStyle = {
  fontSize: '24px',
  marginBottom: '16px'
}

const gridStyle = {
  display: 'flex',
  flexWrap: 'wrap',
  gap: '16px'
}

const itemStyle = {
  flex: '0 0 calc(33.333% - 16px)',
  boxSizing: 'border-box'
}
</script>
